added auth service
RomanBelnitskiy/url-shortener pull request #71
Opened 2024-01-20 15:32 UTC by ZabeidaNazar

2024-01-20 21:13 UTC, RomanBelnitskiy requested changes

2024-01-20 21:13 UTC, RomanBelnitskiy commented on src/main/java/com/example/urlshortener/service/service/impl/AuthServiceImpl.java
> +        repository.save(user);
Юзера з бази треба зберегти в змінну userFromDB, щоб потім можна було дістати його id.

2024-01-20 21:13 UTC, RomanBelnitskiy commented on src/main/java/com/example/urlshortener/service/service/impl/AuthServiceImpl.java
> +
Треба додати:
Map<String, Object> extraClaims = new HashMap<>();
        extraClaims.put("userId", userFromDB.getId());

2024-01-20 21:13 UTC, RomanBelnitskiy commented on src/main/java/com/example/urlshortener/service/service/impl/AuthServiceImpl.java
> +        String jwtToken = jwtService.generateToken(user);
String jwtToken = jwtService.generateToken(extraClaims, userFromDB);

2024-01-20 21:13 UTC, RomanBelnitskiy commented on src/main/java/com/example/urlshortener/service/service/impl/AuthServiceImpl.java
> +        UserDetails user = (UserDetails) authentication.getPrincipal();
Спробуй зробити каст до нашого юзера, щоб id дістати.

2024-01-21 14:47 UTC, ZabeidaNazar commented on src/main/java/com/example/urlshortener/service/service/impl/AuthServiceImpl.java
> +        repository.save(user);
Забув про id, вже виправив

2024-01-21 17:18 UTC, RomanBelnitskiy approved these changes

2024-01-21 17:19 UTC, merged